feat: Create backend project, first step
spacelephant/sonarplanet-services pull request #1
Opened 2018-04-18 15:33 UTC by ftreguer

2018-04-19 08:33 UTC, dlecan requested changes
First feedbacks, I will continue this review.

2018-04-19 08:33 UTC, dlecan commented on .gitignore
> +yarn.lock
Lock file shouldn't be ignored and should be commited into git repo

2018-04-19 08:33 UTC, dlecan commented on package.json
> +  "license": "ISC",
`Apache-2.0` instead
https://spdx.org/licenses/Apache-2.0.html for the license file

2018-04-19 08:34 UTC, dlecan commented on .editorconfig
> +# http://EditorConfig.org
Missing `.ts` files configuration

2018-04-19 08:36 UTC, dlecan commented
Missing `LICENSE` file: https://spdx.org/licenses/Apache-2.0.html

2018-04-23 09:57 UTC, dlecan requested changes
Some feedbacks to integrate

2018-04-26 12:34 UTC, dlecan commented
`yarn start` doen't work:

```
sonarplanet-services (ftreguer-v0 u=)$ yarn start
yarn run v1.6.0
$ node ./dist/app.js
module.js:478
    throw err;
    ^

Error: Cannot find module '/home/dlecan/dev/spacelephant/sonarplanet-services/dist/app.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`yarn run dev` neither:

```
sonarplanet-services (ftreguer-v0 u=)$ yarn dev run
yarn run v1.6.0
$ nodemon ./dist/app.js run
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./dist/app.js run app.js`
module.js:478
    throw err;
    ^

Error: Cannot find module '/home/dlecan/dev/spacelephant/sonarplanet-services/app.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
[nodemon] app crashed - waiting for file changes before starting...
```

2018-04-26 12:37 UTC, dlecan commented on README.md
> +# Note: this config doesn't contain the genesis block.
Is it a problem ?
cc @Nigui

2018-04-26 12:42 UTC, dlecan requested changes

2018-04-26 12:42 UTC, dlecan commented on package.json
> +  "author": "spacelephant",
`author` should be @ftreguer :-)
See https://docs.npmjs.com/files/package.json#people-fields-author-contributors for the format.

2018-04-26 12:42 UTC, dlecan commented on package.json
> +  "repository": "git@github.com:spacelephant/sonarplanet-services.git",
Should be https URL.

2018-04-30 11:07 UTC, ftreguer commented on README.md
> +# Note: this config doesn't contain the genesis block.
I've removed this note

2018-05-01 08:22 UTC, dlecan commented
Handle by #2

2018-05-01 08:22 UTC, closed without merging